on: [push, pull_request]

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - run: git submodule update --init --recursive
      - run: sudo apt-get update
      - run: sudo apt-get --yes install cargo
      - run: cargo test --workspace --verbose
      - run: rustup override set 1.80.1
      - run: cp tests/Cargo_1_68.lock Cargo.lock
      - run: cargo test --workspace --verbose
